### ISSUE TITLE
NoSuchMethodError: toImmutableList

### ISSUE THREAD

**Issue by faveoled** [scala-js/scala-js-env-selenium#129]
```
sbt:livechart> test
[error] stack trace is suppressed; run last Test / jsEnv for the full output
[error] (Test / jsEnv) java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList()'
[error] Total time: 4 s, completed Jul 18, 2023, 12:40:47 PM
sbt:livechart> last Test / jsEnv
[error] java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList()'
[error]         at org.openqa.selenium.remote.server.DefaultDriverFactory.<clinit>(DefaultDriverFactory.java:78)
[error]         at org.scalajs.jsenv.selenium.SeleniumJSEnv$Config.<init>(SeleniumJSEnv.scala:59)
[error]         at org.scalajs.jsenv.selenium.SeleniumJSEnv$Config$.apply(SeleniumJSEnv.scala:127)
[error]         at org.scalajs.jsenv.selenium.SeleniumJSEnv.<init>(SeleniumJSEnv.scala:14)
[error]         at $b7e86287cd76afbb0da5$.$anonfun$$sbtdef$1(/home/user/Dev/Scala/linkchecker-web/build.sbt:9)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:47)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (Test / jsEnv) java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList()'
```
SBT 1.9.2
Scala.js 1.13.2
scalajs-env-selenium 1.1.1
I don't have coursier in project files as the reason for failure in #98 
Selenium driver might not be installed (how do I do that?)

**Comment by sjrd** [comment]
It looks like you have an incompatible version of Guava on your build classpath. See https://stackoverflow.com/q/65973443/1829647

**Comment by faveoled** [comment]
Thanks. Can be solved this way:
```
libraryDependencies += "com.google.guava" % "guava" % "32.1.1-jre"
libraryDependencies += "org.scala-js" %% "scalajs-env-selenium" % "1.1.1"
```
